# frontend/text_strings.py

STRINGS = {
    "en": {
        "title": "PDF Chatbot",
        "intro_text": "This chatbot can answer questions, summarize, and compare multiple PDF documents. To begin, upload your PDF files using the uploader below.",
        "upload_label": "Upload your PDFs",
        "upload_button": "Process PDFs",
        "new_chat_button": "New Chat",
        "delete_chat_button": "Delete Chat",
        "processing_spinner": "Processing your documents...",
        "processing_success": "Documents processed successfully!",
        "processing_error": "An error occurred during processing. Please try again.",
        "welcome_message": "Welcome! Please upload a PDF to get started.",
        "chat_placeholder": "Ask a question about your documents...",
        "ai_thinking": "AI is thinking...",
        "backend_error": "Failed to connect to the backend service.",
        "action_error": "An error occurred while performing the action.",
        "uploaded_files_header": "Uploaded Files",
        "document_actions_header": "Document Actions",
        "select_action_label": "Select an action:",
        "summarize_button": "Summarize All",
        "compare_select_label": "Select files to compare:",
        "compare_button": "Compare Selected",
        "compare_warning": "Please select at least two files to compare.",
        "classify_button": "Classify Topics",
        "delete_success": "Chatroom deleted successfully.",
        "delete_error": "Failed to delete chatroom.",
        "no_files_error": "Please upload at least one PDF file.",
        "manage_chat_header": "Manage Chat",
    },
    "es": {
        "title": "Chatbot de PDF",
        "intro_text": "Este chatbot puede responder preguntas, resumir y comparar múltiples documentos PDF. Para comenzar, suba sus archivos PDF utilizando el cargador de archivos a continuación.",
        "upload_label": "Cargue sus PDFs",
        "upload_button": "Procesar PDFs",
        "new_chat_button": "Nuevo Chat",
        "delete_chat_button": "Eliminar Chat",
        "processing_spinner": "Procesando sus documentos...",
        "processing_success": "¡Documentos procesados con éxito!",
        "processing_error": "Ocurrió un error durante el procesamiento. Por favor, inténtelo de nuevo.",
        "welcome_message": "¡Bienvenido! Por favor, suba un PDF para comenzar.",
        "chat_placeholder": "Haga una pregunta sobre sus documentos...",
        "ai_thinking": "La IA está pensando...",
        "backend_error": "No se pudo conectar al servicio de backend.",
        "action_error": "Ocurrió un error al realizar la acción.",
        "uploaded_files_header": "Archivos Cargados",
        "document_actions_header": "Acciones del Documento",
        "select_action_label": "Seleccione una acción:",
        "summarize_button": "Resumir todo",
        "compare_select_label": "Seleccione archivos para comparar:",
        "compare_button": "Comparar seleccionados",
        "compare_warning": "Por favor, seleccione al menos dos archivos para comparar.",
        "classify_button": "Clasificar temas",
        "delete_success": "Sala de chat eliminada con éxito.",
        "delete_error": "No se pudo eliminar la sala de chat.",
        "no_files_error": "Por favor, suba al menos un archivo PDF.",
        "manage_chat_header": "Administrar Chat",
    },
}