services:
  doc_copilot_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env

  chroma_db:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma
    ports:
      - "8000:8000"

volumes:
  chroma_data: